apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rubik-solver

resources:
  - ../../base
  - route.yaml

images:
  - name: rubik-solver
    newName: image-registry.openshift-image-registry.svc:5000/rubik-solver/rubik-solver
    newTag: latest
